### ISSUE TITLE
Fix extra quotation marks and back slashes in final api html page. 

### ISSUE THREAD

**Issue by ryanrouleau** [JakeC1020/quote-verifier#10]
<img width="1452" alt="screen shot 2015-11-20 at 11 29 21" src="https://cloud.githubusercontent.com/assets/15020000/11308200/0ea2d0e2-8f7a-11e5-8a22-5966d7ff87da.png">

There are extra quotation marks at the beginning and end of the JSON string, as well as several back slashes ('/') in it.  I accounted for this in the extension as a temp fix, but it should be fixed permanently here.

**Comment by hexacyanide** [comment]
Passing a JSON string to `res.json()` is redundant and will result in unintended escaping. You can see [here](https://github.com/strongloop/express/blob/master/lib/response.js#L242) that Express will already call `JSON.stringify()` internally, so objects to be serialized should be passed directly to `res.json()`. The difference between `res.send()` and `res.json()` is a popular question and is explained [here](http://stackoverflow.com/q/19041837).

**Comment by ryanrouleau** [comment]
Good explanation, Evan.  Fixed.
