### ISSUE TITLE
Wikiquote URLs are sometimes case sensitive.

### ISSUE THREAD

**Issue by ryanrouleau** [JakeC1020/quote-verifier#2]
It seems that some articles (for example, Albert Einstein) automatically correct for trying to access wikiquote.org/wiki/albert_einstein (note the lower case name), while others do not (for example, Carl Sagan).  This means to access Carl Sagan's page, the URL has to be wikiquote.org/wiki/Carl_Sagan, and not wikiquote.org/wiki/carl_sagan.  We have to make the first letter capitalized and the letter after a space capitalized in cleanName().

**Comment by JakeC1020** [comment]
I wonder if we could do a try, catch type thing, where if we have a sequence of urls to try? For example, first try carl_sagan, if 404, try Carl_Sagan, etc.

**Comment by JakeC1020** [comment]
This could also be motivation to move onto an afterthought where after we scrape, we could throw it in a database, as we could store whether it was carl_sagan or Carl_Sagan, as well as the quotes?

**Comment by ryanrouleau** [comment]
So it seems that wikiquote always accepts the name in the URL IF the first letter of the first/last name are capitalized, but doesn't always accepts the name if it's entirely lowercase.  Possible solution: http://stackoverflow.com/questions/7467381/capitalize-the-first-letter-of-every-word

**Comment by ryanrouleau** [comment]
Fixed.
