### ISSUE TITLE
Scraper.js not functioning

### ISSUE THREAD

**Issue by ryanrouleau** [JakeC1020/quote-verifier#3]
There are errors with callbacks when trying to access /api?auth.....  
I might have written variables wrong (not 100% sure when to use var and when not to use it) that may be the problem.
I believe that if we can get it working, then it should be finished (for now)!

Scrape function is pretty ugly.  Could be refactored at some point.

**Comment by JakeC1020** [comment]
Looks like there was an issue with it firing the call back before the request function finished. Fixed that, and it is now able to recognize an author page, just is having issues with finding the quote itself. I'll push up those changes so you can take a look.

**Comment by ryanrouleau** [comment]
Fixed issues with not finding quote.  It's now functioning!
